# Generated by Django 4.0.6 on 2022-07-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='favourite',
        ),
    ]
